apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cron.name }}
spec:
  schedule: {{ .Values.cron.job.schedule }}
  successfulJobsHistoryLimit: {{ .Values.cron.job.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.cron.name }}
              image: "{{ .Values.cron.image.repository }}:{{ .Values.cron.image.tag }}"
              envFrom:
                - secretRef:
                    name: {{ .Values.secret.name }}
          restartPolicy: {{ .Values.cron.pod.restartPolicy }}
