apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  AUTH_KEY: {{ .Values.secret.authKey }}
  NAME: {{ .Values.secret.dnsRecord }}
  RECORD_ID: {{ .Values.secret.recordId }}
  ZONE_ID: {{ .Values.secret.zoneId }}
