apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudflare-ddns
              image: kubitodev/kubernetes-cloudflare-ddns:latest
              envFrom:
                - secretRef:
                    name: cloudflare-ddns
          restartPolicy: OnFailure
