name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump Version and Push Tag
        id: autotag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: patch
      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.io/kubitodev/kubernetes-cloudflare-ddns
          tags: |
            # Gets the new_tag output from the previous step
            type=semver,pattern={{version}},value=${{ steps.autotag.outputs.new_tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.autotag.outputs.new_tag }}
          flavor: |
            latest=true
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          platforms: linux/amd64,linux/arm64, linux/arm/v7, linux/arm/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
